blockExoticSubdeps: true

catalog:
  '@types/node': ^24 
  effect: 4.0.0-rc.115
  oxfmt: ^0.68.0
  oxlint: ^1.83.0
  typescript: ^6

engineStrict: true

packages:
  - apps/*
  - packages/*

minimumReleaseAge: 10080

