blockExoticSubdeps: true

catalog:
  '@effect/tsgo': ^0.45.0
  '@types/node': ^24 
  effect: 4.0.0-rc.115
  oxfmt: ^0.68.0
  oxlint: 1.82.0
  oxlint-tsgolint: ^7.0.2001
  typescript: ^6

engineStrict: true

packages:
  - apps/*
  - packages/*

minimumReleaseAge: 10080
