create table public.role (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  source_write boolean not null default false,
  source_read boolean not null default false,
  member_read boolean not null default false,
  member_write boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.role (name, source_write, source_read, member_read, member_write)
values
  ('owner', true, true, true, true),
  ('member', false, false, false, false);

create table public."user" (
  id uuid primary key references auth.users (id) on delete cascade,
  role_id uuid not null references public.role (id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.source (
  id bigint generated by default as identity primary key,
  type text not null,
  url text not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint source_type_valid check (type = any (array['web_scrape']::text[])),
  constraint source_notes_null_outside_web_scrape check (
    type = 'web_scrape' or notes is null
  )
);

create index user_role_id_idx on public."user" (role_id);
create index user_created_at_desc_idx on public."user" (created_at desc);
create index user_updated_at_desc_idx on public."user" (updated_at desc);
create index source_type_idx on public.source (type);

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger role_set_updated_at
before update on public.role
for each row execute function public.set_updated_at();

create trigger user_set_updated_at
before update on public."user"
for each row execute function public.set_updated_at();

create trigger source_set_updated_at
before update on public.source
for each row execute function public.set_updated_at();

create function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public."user" (id, role_id)
  values (new.id, (select id from public.role where name = 'member'));
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

alter table public.role enable row level security;
alter table public."user" enable row level security;
alter table public.source enable row level security;

revoke all on table public.role, public."user", public.source from public, anon, authenticated;
revoke all on sequence public.source_id_seq from public, anon, authenticated;
revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.handle_new_auth_user() from public, anon, authenticated;
